# Generated by Django 2.2.10 on 2021-11-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211111_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=512, null=True, verbose_name='Текст ответа'),
        ),
    ]
